######################################################################
# Automatically generated by qmake (2.00a) Sun Dec 25 00:54:30 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h
SOURCES += Calculator.cpp
